console.log('Sabit  ');
console.log("I am Sabit ");
console.log("I am a good boy ");
console.log("I have a brother ");
console.log("My brother's name is saad ");
console.log("My father's name is Golam Mortuza ");
console.log("My mother's name is Logna");
console.log("I am in class III");
console.log("I am in section A");
console.log("My brother is in class V");
console.log("I have guest in my house");
console.log("I dont no what to do bye");
console.log("Coding is very hard");
console.log("But coding is fun");
console.log("You can have a good knowlege about coding in 10 minutes");
console.log("Learn more about coding");
console.log("Learn harder about coding")
console.log("Our country name is bangladesh");
console.log("Our  neighbor country is india");
console.log("Our neighbor country name is china");
console.log("Our neighbor country name is myanmar");
console.log(4+8);
const greeting = "Hello, World! 🌍";
console.log(greeting);
console.log("I have 100 friends😊");
console.log("I am going to brush my teeth");
console.log("I will go to school in a few minutes");
console.log(3-2);
console.log("I have lunch now");
console.log("I will go to bongobondhu tunnel later")