console.log('Sabit  ');
console.log("I can have so many words in a seconnd");
console.log("I am Sabit ");
console.log("I can have so many words in a seconnd");
console.log("I am a good boy ");
console.log("I can have so many words in a seconnd");
console.log("I have a brother ");
console.log("I can have so many words in a seconnd");
console.log("My brother's name is saad ");
console.log("I can have so many words in a seconnd");
console.log("My father's name is Golam Mortuza ");
console.log("I can have so many words in a seconnd");
console.log("My mother's name is Logna");
console.log("I can have so many words in a seconnd");
console.log("I am in class III");
console.log("I can have so many words in a seconnd");
console.log("I am in section A");
console.log("I can have so many words in a seconnd");
console.log("My brother is in class V");
console.log("I can have so many words in a seconnd");
console.log("I have guest in my house");
console.log("I can have so many words in a seconnd");
console.log("I dont no what to do bye");
console.log("I can have so many words in a seconnd");
console.log("Coding is very hard");
console.log("I can have so many words in a seconnd");
console.log("But coding is fun");
console.log("I can have so many words in a seconnd");
console.log("You can have a good knowlege about coding in 10 minutes");
console.log("I can have so many words in a seconnd");
console.log("Learn more about coding");
console.log("I can have so many words in a seconnd");
console.log("Learn harder about coding")
console.log("I can have so many words in a seconnd");
console.log("Our country name is bangladesh");
console.log("I can have so many words in a seconnd");
console.log("Our  neighbor country is india");
console.log("I can have so many words in a seconnd");
console.log("Our neighbor country name is china");
console.log("I can have so many words in a seconnd");
console.log("Our neighbor country name is myanmar");
console.log("I can have so many words in a seconnd");
console.log(4 + 8);
console.log("I can have so many words in a seconnd");
const greeting = "Hello, World! 🌍";
console.log("I can have so many words in a seconnd");
console.log(greeting);
console.log("I can have so many words in a seconnd");
console.log("I have 100 friends😊");
console.log("I can have so many words in a seconnd");
console.log("I am going to brush my teeth");
console.log("I can have so many words in a seconnd");
console.log("I will go to school in a few minutes");
console.log("I can have so many words in a seconnd");
console.log(3 - 2);
console.log("I can have so many words in a seconnd");
console.log("I have lunch now");
console.log("I can have so many words in a seconnd");
console.log("I will go to bongobondhu tunnel later")
console.log("I can have so many words in a seconnd");
console.log("I have come back from bongobondhu tunnel");
console.log("I can have so many words in a seconnd");
console.log("I can have so many words in a seconnd");
console.log("My brother just have a new coding file");
console.log("I wake up from sleep");
console.log("then I brush my teeth");
console.log("then I nave breakfast");
console.log("then I go down and paly with my brother");
console.log("then I have lunch");
console.log("then I come to practice coding");
console.log(6 / 3);
console.log(6945 * 4563);
console.log(789 - 345);
